|-
#cloud-config
hostname: @@{name}@@
users:
  - name: @@{Cred_OS.username}@@
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
chpasswd:
  list: |
    @@{Cred_OS.username}@@:@@{Cred_OS.secret}@@
  expire: False
ssh_pwauth: True
